### ISSUE TITLE
Are you using the oracle accuracy got on the test set?

### ISSUE THREAD

**Issue by ZZQ321** [lingeringlight/DomainDrop#2]

**Comment by YAaNnGg** [comment]
I have encountered the same issue. The test performance of the best validation model doesn't align with the results in the paper. In PACS dataset, I got 81.66, 79.43, 95.35, and 79.09 for A, C, P, and S test domains, which are 84.47, 80.50, 96.83, and 84.83 in the paper. How to deal with it?
